import { GetServerSidePropsContext } from "next";
import { useRouter } from "next/router";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import {
  GrowthBookContext,
  GrowthBook,
  useGrowthBook,
} from "@growthbook/growthbook-react";
import { useState, useEffect, useContext } from "react";
import styles from "../styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

const FEATURES_ENDPOINT =
  "http://localhost:3100/api/features/prod_AketOD945Ctes2OD4B8CrO8cuoNNQe7VzJTWGhdFc";

const growthbook = new GrowthBook({
  trackingCallback: (experiment, result) => {
    console.log("Viewed Experiment", experiment, result);
  },
});

export async function getServerSideProps(context: GetServerSidePropsContext) {
  const res = await fetch(FEATURES_ENDPOINT);
  const json = await res.json();

  growthbook.setFeatures(json.features);

  growthbook.setAttributes({
    id: "123",
    loggedIn: true,
    deviceId: "abcdef123456",
    employee: true,
    company: "acme",
    country: "US",
    browser: "nextjs-node",
    url: context.req.url,
  });

  const showWelcomeBanner = growthbook.feature("welcome-message").on;

  return {
    props: { showWelcomeBanner },
  };
}

export default function Home({
  showWelcomeBanner: _showWelcomeBanner,
}: {
  showWelcomeBanner: boolean;
}) {
  const router = useRouter();
  const growthbook = useGrowthBook();

  const [showWelcomeBanner, setShowWelcomeBanner] =
    useState(_showWelcomeBanner);

  useEffect(() => {
    if (!growthbook) return;

    fetch(FEATURES_ENDPOINT)
      .then((res) => res.json())
      .then((json) => {
        growthbook.setFeatures(json.features);
        setShowWelcomeBanner(growthbook.feature("welcome-message").on);
      });
  }, [growthbook]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {showWelcomeBanner && (
          <h1>Welcome to Next.js equipped w/ SSR Growthbook</h1>
        )}
      </main>
    </>
  );
}
