import { GetServerSidePropsContext } from "next";
import Head from "next/head";
import { useGrowthBook } from "@growthbook/growthbook-react";
import { useState } from "react";
import styles from "../styles/Home.module.css";
import { FEATURES_ENDPOINT, growthbook } from "./_app";
import Link from "next/link";

export async function getServerSideProps(context: GetServerSidePropsContext) {
  const res = await fetch(FEATURES_ENDPOINT);
  const json = await res.json();

  growthbook.setFeatures(json.features);

  growthbook.setAttributes({
    id: "123",
    loggedIn: true,
    deviceId: "abcdef123456",
    employee: false,
    company: "acme",
    country: "US",
    browser: "nextjs-node",
    url: context.req.url,
  });

  const showWelcomeBanner = growthbook.feature("welcome-message").on;

  return {
    props: { showWelcomeBanner },
  };
}

export default function NoWelcomePage({
  showWelcomeBanner: _showWelcomeBanner,
}: {
  showWelcomeBanner: boolean;
}) {
  console.log("DEBUG initial render", { _showWelcomeBanner });

  const [showWelcomeBanner, setShowWelcomeBanner] = useState(
    !!_showWelcomeBanner
  );

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {showWelcomeBanner && (
          <h1>Welcome to Next.js equipped w/ SSR Growthbook</h1>
        )}
        <h2>
          We shouldn&apos;t see a welcome banner above this. (W/ Override rule
          &quot;url not equal to /no-welcome&quot;)
        </h2>
        <Link href="/">Go to Welcome page</Link>
      </main>
    </>
  );
}
